<?php

module_load_include('inc', 'uuid');

/**
 * Wrapper function around 'entity_save()' that supports saving entities based
 * on their UUID.
 *
 * This function will try to find the local entity ID if it exists and update
 * the node accordingly, otherwise a new node will be saved.
 */
function uuid_entity_save($entity_type, $entity) {
  // Metadata wrapper for the entity.
  $entity_wrapper = entity_metadata_wrapper($entity_type, $entity);

  // Fetch and set the entity ID.
  $id_property = $entity_wrapper->entityKey('id');
  $id = uuid_find($entity->uuid, $entity_type, $id_property);
  if (!empty($id)) {
    $entity->{$id_property} = $id;
  }

  // Fetch and set the entity version ID.
  if (isset($entity->vuuid)) {
    $vid_property = $entity_wrapper->entityKey('revision');
    $vid = uuid_find($entity->vuuid, $entity_type . '_revision', $vid_property, 'vuuid');
    if (!empty($vid)) {
      $entity->{$vid_property} = $vid;
    }
  }

  // Save the entity.
  entity_save($entity_type, $entity);
}
