<?php

/**
 * @file
 * Main module functions for the uuid module.
 */

/**
 * Include main API functions.
 */
include_once './uuid.inc';

/**
 * Include the Entity API implementation of the UUID API.
 */
include_once './uuid.entity.inc';

/**
 * Include implementations for all core modules.
 *
 * Instead of having separate modules for all core implementations this file
 * implements all of them in their own name space. In some cases this adds some
 * unecessary code weight, but instead it saves us from module mania.
 */
include_once './uuid.core.inc';

/**
 * Implements of hook_menu().
 */
function uuid_menu() {
  return array(
    'admin/config/system/uuid' => array(
      'title' => 'Universally unique identifiers',
      'description' => 'Configure universally unique identifiers.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('uuid_admin_form'),
      'access arguments' => array('administer uuid'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'uuid.admin.inc',
    ),
  );
}

/**
 * Implements of hook_permission().
 */
function uuid_permission() {
  return array(
    'administer uuid' => array(
      'title' => t('Administer UUID'),
      'description' => t('Allows configuration of the UUID module and APIs.'),
    ),
  );
}

/**
 * Implements of hook_module_implements_alter().
 *
 * Moves the hook_entity_info_alter() Implements to the bottom so it is
 * invoked after all modules relying on the entity API.
 *
 * @see uuid_entity_info_alter()
 */
function uuid_module_implements_alter(&$Implementss, $hook) {
  if ($hook == 'entity_info_alter') {
    // Move our hook Implements to the bottom.
    $group = $Implementss['uuid'];
    unset($Implementss['uuid']);
    $Implementss['uuid'] = $group;
  }
}
