<?php

/**
 * @file
 *   UUID path module functions.
 */

/**
 * Implements hook_entity_uuid_load().
 */
function uuid_path_entity_uuid_load(&$entities, $entity_type) {
  _uuid_path_load_url_aliases($entities, $entity_type);
  _uuid_path_load_menu_link($entities, $entity_type);
}

/**
 * Implements hook_entity_uuid_save().
 */
function uuid_path_entity_uuid_save(&$entity, $entity_type) {
  _uuid_path_save_url_aliases($entity, $entity_type);
  _uuid_path_save_menu_link($entity, $entity_type);
}

/**
 * Loads url aliases in the corresponding entity.
 */
function _uuid_path_load_url_aliases(&$entities, $entity_type) {
  $info = entity_get_info($entity_type);
  // we only care about entities with URLs.
  if (!isset($info['uri callback'])) {
    return;
  }

  $callback = $info['uri callback'];
  foreach ($entities as $id => $entity) {
    $path = $callback($entity);
    $aliases = _uuid_path_url_alias_load($path['path']);

    // Ignore local IDs.
    foreach($aliases as &$alias) {
      unset($alias->pid);
      unset($alias->source);
    }

    $entities[$id]->url_alias = $aliases;
  }
}

/**
 * Loads a menu link in the corresponding entity.
 */
function _uuid_path_load_menu_link(&$entities, $entity_type) {
  module_load_include('inc', 'uuid', 'uuid.features.menu');

  if ($entity_type === 'node') {
    foreach ($entities as $id => $entity) {
      if (isset($entity->nid)) {
        $mlid = _uuid_path_mlid_load($entity);
        if ($mlid) {
          $link = menu_link_load($mlid);
          uuid_menu_link_make_universal($link, TRUE);
          $entities[$id]->menu_link = $link;
        }
      }
    }
  }
}

/**
 * Saves the received url aliases.
 */
function _uuid_path_save_url_aliases(&$entity, $entity_type) {
  $info = entity_get_info($entity_type);

  // We only care when there is a url callback
  if (!isset($info['uri callback'])) {
    return FALSE;
  }

  $callback = $info['uri callback'];
  $uri = $callback($entity);
  $path = $uri['path'];

  // Delete existing aliases.
  path_delete(array('source' => $path));

  // Continue if aliases are present.
  if(empty($entity->url_alias)) {
    return FALSE;
  }

  foreach ($entity->url_alias as $alias) {
    $entry = (array) $alias;
    $entry['source'] = $path;
    path_save($entry);
  }
}

/**
 * Saves the received menu links.
 */
function _uuid_path_save_menu_link(&$entity, $entity_type) {
  module_load_include('inc', 'uuid', 'uuid.features.menu');

  if ($entity_type == 'node') {
    if (isset($entity->nid)) {
      $mlid = _uuid_path_mlid_load($entity);
      if ($mlid) {
        menu_link_delete($mlid);
      }
    }

    if (isset($entity->menu_link)) {
      $link = $entity->menu_link;
      uuid_menu_link_make_local($link);
      menu_link_save($link);
    }
  }
}

/**
 * Loads all aliases associated with a path.
 *
 * @param $path
 *   The source path to look up.
 *
 * @return
 *   Array of paths or NULL if none found.
 */
function _uuid_path_url_alias_load($path) {
  return db_select('url_alias')
    ->condition('source', $path)
    ->fields('url_alias')
    ->execute()
    ->fetchAll(PDO::FETCH_OBJ);
}

/**
 * Loads menu link ID associated with an entity.
 *
 * @param $entity
 *   The entity used to get the menu link ID.
 *
 * @return
 *   A menu link ID
 */
function _uuid_path_mlid_load($entity) {
  $mlid = FALSE;
  $menu_name = strtok(variable_get('menu_parent_' . $entity->type, 'main-menu:0'), ':');
  // Give priority to the default menu
  $type_menus = variable_get('menu_options_' . $entity->type, array('main-menu' => 'main-menu'));
  if (in_array($menu_name, $type_menus)) {
    $mlid = db_query_range("SELECT mlid FROM {menu_links} WHERE link_path = :path AND menu_name = :menu_name AND module = 'menu' ORDER BY mlid ASC", 0, 1, array(
      ':path' => 'node/' . $entity->nid,
      ':menu_name' => $menu_name,
    ))->fetchField();
  }
  // Check all allowed menus if a link does not exist in the default menu.
  if (!$mlid && !empty($type_menus)) {
    $mlid = db_query_range("SELECT mlid FROM {menu_links} WHERE link_path = :path AND module = 'menu' AND menu_name IN (:type_menus) ORDER BY mlid ASC", 0, 1, array(
      ':path' => 'node/' . $entity->nid,
      ':type_menus' => array_values($type_menus),
    ))->fetchField();
  }
  return $mlid;
}
