<?php

module_load_include('inc', 'uuid');

/**
 * Implements hook_comment_presave().
 */
function uuid_comment_comment_presave($comment) {
  // We generate the UUID here so it can be used by other hooks.
  if (empty($comment->uuid)) {
    $comment->uuid = uuid_uuid();
  }
}

/**
 * Searches for a comment by its UUID.
 */
function uuid_comment_find($uuid) {
  return uuid_find($uuid, 'comment', 'cid');
}
