<?php

/**
 * Implementation hook_uuid_info().
 */
function uuid_ossp_uuid_info() {
  $sources = array();
  if (function_exists('uuid_make')) {
    $sources['ossp'] = array(
      'title' => t('OSSP Extension'),
      'callback' => 'uuid_ossp',
    );
  }
  return $sources;
}

/**
 * Generates a UUID using the (somewhat broken) OSSP PHP extension.
 *
 * @see http://www.ossp.org/pkg/lib/uuid
 */
function uuid_ossp() {
  $v4 = NULL;
  $out = '';
  uuid_create(&$v4);
  uuid_make($v4, UUID_MAKE_V4);
  uuid_export($v4, UUID_FMT_STR, &$out);
  return $out;
}
