<?php

module_load_include('inc', 'uuid');

/**
 * Implements hook_node_presave().
 */
function uuid_node_node_presave($node) {
  if (empty($node->uuid)) {
    $node->uuid = uuid_uuid();
  }

  if (1 == $node->revision) {
    $node->vuuid = uuid_uuid();
  }

  if (empty($node->vuuid)) {
    $node->vuuid = uuid_uuid();
  }
}

/**
 * Searches for a node by its UUID.
 */
function uuid_node_find($uuid) {
  return uuid_find($uuid, 'node', 'nid');
}
